#!/bin/bash

SOURCE_DIR=${PWD}

TITLE=${SOURCE_DIR##*/}
AUTHOR='Light Novels'
COVER='cover.jpg'

XMLSTARLET='xmlstarlet ed -N n=http://www.idpf.org/2007/opf -N dc=http://purl.org/dc/elements/1.1/'

TMPDIR=$(mktemp -d '/dev/shm/epub-gen.XXXXXXXX')

cd "${TMPDIR}"

echo -n 'application/epub+zip' > mimetype

mkdir 'META-INF'
echo '<?xml version="1.0" encoding="UTF-8"?>
<container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container">
    <rootfiles>
        <rootfile full-path="content.opf" media-type="application/oebps-package+xml"/>
   </rootfiles>
</container>' > 'META-INF/container.xml'

CONTENT_OPF='<?xml version="1.0" encoding="utf-8"?> <package xmlns="http://www.idpf.org/2007/opf" version="3.0" unique-identifier="title"><metadata xmlns:dc="http://purl.org/dc/elements/1.1/"><meta name="cover" content="cover.jpg"/></metadata><manifest><item id="cover.xhtml" href="cover.xhtml" media-type="application/xhtml+xml"/><item id="cover.jpg" href="cover.jpg" media-type="image/jpeg"/><item id="ncx" href="toc.ncx" media-type="application/x-dtbncx+xml"/></manifest><spine toc="ncx"><itemref idref="cover.xhtml"/></spine><guide/></package>'
TOC_NCX='<?xml version="1.0" encoding="UTF-8"?> <ncx xmlns="http://www.daisy.org/z3986/2005/ncx/"><head/><navMap><navPoint playOrder="1" id="cover.xhtml"><navLabel><text>Cover</text></navLabel><content src="cover.xhtml"/></navPoint></navMap></ncx>'

CONTENT_OPF=$(${XMLSTARLET} --subnode '/n:package/n:metadata' -t elem -n 'dc:title' -v "${TITLE}" <<<${CONTENT_OPF})
CONTENT_OPF=$(${XMLSTARLET} --subnode '/n:package/n:metadata' -t elem -n 'dc:creator' -v "${AUTHOR}" <<<${CONTENT_OPF})

gen_cover() {
if [ -f "${SOURCE_DIR}/cover.jpg" ]; then
    cp "${SOURCE_DIR}/cover.jpg" .
else
    convert \
        -background white -fill black \
        -size '480x640' -gravity center \
        -font 'Noto-Serif-Regular' -pointsize 64 caption:"${TITLE}" \
        'cover.jpg'
fi

cat <<eof > 'cover.xhtml'
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
  "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>Cover</title>
  </head>
  <body style="padding:0;margin:0;">
    <svg xmlns="http://www.w3.org/2000/svg" height="100%" preserveAspectRatio="xMidYMid meet" version="1.1" viewBox="0 0 480 640" width="100%" xmlns:xlink="http://www.w3.org/1999/xlink">
      <image width="480" height="640" xlink:href="cover.jpg" src="cover.jpg" style="padding:0;margin:0;"/>
    </svg>
  </body>
</html>
eof
}

NAVPLAYORDER=2

while IFS= read -r TXTFILE; do
    TXTFILE_EMBED="${TXTFILE#${SOURCE_DIR}/*}"
    echo -ne "\r                                                                                \r${TXTFILE_EMBED}"

    TXTFILE_EMBED_BASENAME=${TXTFILE_EMBED%.*}
    TXTFILE_EMBED="${TXTFILE_EMBED_BASENAME}.xhtml"

    mkdir -p "${TXTFILE_EMBED}"
    rmdir "${TXTFILE_EMBED}"

    echo '<?xml version="1.0" encoding="utf-8"?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<meta content="http://www.w3.org/1999/xhtml; charset=utf-8" http-equiv="Content-Type"/>
<link href="stylesheet.css" type="text/css" rel="stylesheet"/>
</head>
<body>
' > "${TXTFILE_EMBED}"
sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g; s/"/\&quot;/g; s/'"'"'/\&#39;/g; s/$/<br\/>/g;' "${TXTFILE}" >> "${TXTFILE_EMBED}"

echo '</body>
</html>' >> "${TXTFILE_EMBED}"

    CONTENT_OPF=$(${XMLSTARLET} --subnode '/n:package/n:manifest' -t elem -n "item id=\"${TXTFILE_EMBED_BASENAME}\" href=\"${TXTFILE_EMBED}\" media-type=\"application/xhtml+xml\"" <<<${CONTENT_OPF})
    CONTENT_OPF=$(${XMLSTARLET} --subnode '/n:package/n:spine' -t elem -n "itemref idref=\"${TXTFILE_EMBED_BASENAME}\"" <<<${CONTENT_OPF})

    TOC_NCX=$(xmlstarlet ed -N n='http://www.daisy.org/z3986/2005/ncx/' --subnode '/n:ncx/n:navMap' -t 'elem' -n "navPoint playOrder=\"${NAVPLAYORDER}\" id=\"${TXTFILE_EMBED_BASENAME}\"" <<<${TOC_NCX})
    TOC_NCX=$(xmlstarlet ed -N n='http://www.daisy.org/z3986/2005/ncx/' --subnode "/n:ncx/n:navMap/n:navPoint[@id=\"${TXTFILE_EMBED_BASENAME}\"]" -t 'elem' -n 'navLabel' <<<${TOC_NCX})
    TOC_NCX=$(xmlstarlet ed -N n='http://www.daisy.org/z3986/2005/ncx/' --subnode "/n:ncx/n:navMap/n:navPoint[@id=\"${TXTFILE_EMBED_BASENAME}\"]/n:navLabel" -t 'elem' -n 'text' -v "${TXTFILE_EMBED_BASENAME//\// - }" <<<${TOC_NCX})
    TOC_NCX=$(xmlstarlet ed -N n='http://www.daisy.org/z3986/2005/ncx/' --subnode "/n:ncx/n:navMap/n:navPoint[@id=\"${TXTFILE_EMBED_BASENAME}\"]" -t 'elem' -n "content src=\"${TXTFILE_EMBED}\"" <<<${TOC_NCX})

    NAVPLAYORDER=$((${NAVPLAYORDER} + 1))
done<<<$(find "${SOURCE_DIR}" -type f -name '*.txt' | sort -V)

echo -e "${CONTENT_OPF}" > 'content.opf'
echo -e "${TOC_NCX}" > 'toc.ncx'

gen_cover

#bash

#N
#read xxx
echo -e "\r                                                                                \r${TITLE}.epub"


zip -q -r -9 'epub.zip' *
mv 'epub.zip' "${SOURCE_DIR}/${TITLE}.epub"

cd
rm -rf "${TMPDIR}"
