#!/bin/bash

# Sizes in megabytes
START_SIZE=16000
INCREASE_SIZE=1000

# $1: Filename
# $2: Label
# $3: Size in megabytes
create_ntfs_file() {
    dd if=/dev/zero count=${3} bs=1M > "${1}" 2>/dev/null || return 1
    mkntfs -QCF -L "${2}" "${1}" 2>/dev/null || return 1
}

# $1: Filename
ntfs_shrink_fit() {
    new_size=$(ntfsresize -i "${1}" | sed -ne '12{p}' | cut -d ' ' -f 5)
    echo 'y' | ntfsresize -fs "${new_size}" "${1}" || return 1
    truncate -s "${new_size}" "${1}"
}


# $1: Filename
# $2: Size increment in megabytes
ntfs_increase_size() {
    dd if=/dev/zero count=${2} bs=1M >> "${1}" || return 1
    new_size=$(ls -l "${1}" | cut -d ' ' -f 5) || return 1

    echo 'y' | ntfsresize -fs "${new_size}" "${1}" || return 1
}

# $1: Filename
# $2: Mount Dir
ntfs_mount() {
    sudo mount -t 'ntfs-3g' -o "loop,gid=$(id -u),uid=$(id -g)" "${1}" "${2}/" || return 1
}

# $1: Filename
ntfs_unmount() {
    sudo umount "${1}" || return 1
}

# $1: Filename
ntfs_finish() {
    ntfsfix -d "${1}" || return 1
}

copy_data() {
    #rsync --inplace --size-only --delete-before --whole-file -r "${SOURCE_DIR}/" "${MOUNT_DIR}" || return 1
    while IFS= read -r path; do
        echo "${path}"
        [ -f "${1}/${path%/*}" ] || [ -d "${2}/${path%/*}" ] || mkdir -p "${2}/${path%/*}" || return 1
        if [ -e "${2}/${path}" ] || cp "${1}/${path}" "${2}/${path}"; then
            continue
        else
            rm -f "${2}/${path}"
            return 1
        fi
    done <<<$(find "${1}" -type f -printf "%P\n")
}

failed() {
    echo 'An error occurred'
    (cd "${TMPDIR}" && bash)
    exit
}

SOURCE_DIR=$(readlink -f "${1}")
DEST_FILE="${SOURCE_DIR}.img"

TMPDIR=$(mktemp -d '/dev/shm/ntfs-gen-from-folder.XXXXXXXX')
NTFS_FILE="${TMPDIR}/disk.img"
MOUNT_DIR="${NTFS_FILE}.mount"
mkdir -p "${MOUNT_DIR}"

create_ntfs_file "${NTFS_FILE}" "${SOURCE_DIR##*/}" "${START_SIZE}" || failed
ntfs_mount "${NTFS_FILE}" "${MOUNT_DIR}" || failed
cp -vrf "${SOURCE_DIR}"/* "${MOUNT_DIR}" || failed
ntfs_unmount "${NTFS_FILE}" || failed
ntfs_shrink_fit "${NTFS_FILE}" || failed
ntfs_finish "${NTFS_FILE}" || failed

echo mv "${NTFS_FILE}" "${DEST_FILE}"
mv "${NTFS_FILE}" "${DEST_FILE}"

rm -rf "${TMPDIR}"
