#!/bin/bash

case "$(arch)" in
    i386|i686)
        ARCH=x86
        ;;

    x86_64)
        ARCH=x86_64
        ;;
        
    *)
        echo "patchelf: Not available on this architecture"
        exit
        ;;
esac

ScriptDir=$(readlink -f "${BASH_SOURCE%/*}")

"${ScriptDir}/Linux.${ARCH}/patchelf" "$@"

